--- #YAML:1.0
name:               File-PerlMove
version:            0.06
abstract:           move files using Perl power
author:
    - Johan Vromans (jvromans@squirrel.nl)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Basename:  0
    File::Path:      0
    Getopt::Long:    2
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
